### ISSUE TITLE
Data modelling for assertions collected over the summer

### ISSUE THREAD

**Issue by tla** [erc-releven/.github#14]
[Assignment_8-Initial_list-Rozsa.xlsx](https://github.com/erc-releven/.github/files/12455421/Assignment_8-Initial_list-Rozsa.xlsx)
[Dataset trial Aleksandar.xlsx](https://github.com/erc-releven/.github/files/12455420/Dataset.trial.Aleksandar.xlsx)
[RELEVEN DATASET READ, L - Aristakes ch 1-10.xlsx](https://github.com/erc-releven/.github/files/12455419/RELEVEN.DATASET.READ.L.-.Aristakes.ch.1-10.xlsx)
[IDENTITY_PEOPLE_11TH CENTURY.xlsx](https://github.com/erc-releven/.github/files/12455430/IDENTITY_PEOPLE_11TH.CENTURY.xlsx)

**Comment by laletuver1** [comment]
Issued for Data Modelling Sub-Project.
