### ISSUE TITLE
Curation of death-factoid data from PBW

### ISSUE THREAD

**Issue by tla** [erc-releven/.github#2]

**Comment by Aaleks93** [comment]
Here's my batch of PBW death-factoids completed:

[C11 PBW Death records, Aleksandar.xlsx](https://github.com/erc-releven/.github/files/10537293/C11.PBW.Death.records.Aleksandar.xlsx)

**Comment by Aaleks93** [comment]
also related to issue #1, revised version of the death factoids, completed. you can access the updated spreadsheet through [this link](https://ucloud.univie.ac.at/index.php/f/797833040)

**Comment by martonrozsa88** [comment]
I finished the revision of my death factoid spreadsheet. I added two columns for external source and external source loc (not many entries there though), and made some minor changes. [Here is the link for the document.](https://ucloud.univie.ac.at/index.php/f/805483617)

**Comment by Aaleks93** [comment]
The spreadsheet with death records has been updated with sources on which I based the datings where my name is the authority. Therefore, the file from 21.11.2023 has been updated to the file named "C11 PBW Death records, AA_revised version_09.01.2024." xlsx, accessible here https://ucloud.univie.ac.at/index.php/f/797833040
