### ISSUE TITLE
Bring Data Management Plan up to date

### ISSUE THREAD

**Issue by tla** [erc-releven/.github#26]
We submitted a data management plan to the EU in December 2021; this would be an excellent point to review it and bring it up to date. The original plan is here: https://docs.google.com/document/d/17C5PjMW3jQd-u_k7OjMrm69FbQ4ounaKbAfgNuZdd48/edit

**Comment by laletuver1** [comment]
comment moved to scientific report #28

**Comment by laletuver1** [comment]
[Updated Version](https://docs.google.com/document/d/1nrIrH4eo3T4X7voMMoYv1cIUKwd7ohnq/edit?usp=drive_link&ouid=101289591003560298742&rtpof=true&sd=true)
