### ISSUE TITLE
Possible data extraction from Syriaca

### ISSUE THREAD

**Issue by laletuver1** [erc-releven/.github#35]
[Syriaca](https://syriaca.org/index.html)

**Comment by laletuver1** [comment]
@tla  [Syriaca.org documentation](https://syriaca.org/documentation/index.html)

**Comment by tla** [comment]
To extract data from Syriaca the way I envisioned would involve mapping from their TEI usage into an ontology that we are using. For the number of entries there relevant to the 11th century and the amount of information, I'm not sure doing this makes sense. We can still use it as an external authority to identify people though.
