### ISSUE TITLE
Second financial report

### ISSUE THREAD

**Issue by tla** [erc-releven/.github#43]
as you can see the session for our second reporting has been opened in the Participant Portal!
So I would need the following things:
 
Time recordings of all team members, charging costs to RELEVEN in period 2
Attached you can find the “other costs” Excel list, with questions of mine in the blue column. Could you answer them and send the file back to me?
Also attached the Word document of the “Technical Part”, meaning the written part of our reporting. I would need you to answer questions 1., 2.1 and 2.3.1. The rest will be filled by me!
 
All the best and thanks a lot!

**Comment by tla** [comment]
as you can see the session for our second reporting has been opened in the Participant Portal!
So I would need the following things:
 
Time recordings of all team members, charging costs to RELEVEN in period 2
Attached you can find the “other costs” Excel list, with questions of mine in the blue column. Could you answer them and send the file back to me?
Also attached the Word document of the “Technical Part”, meaning the written part of our reporting. I would need you to answer questions 1., 2.1 and 2.3.1. The rest will be filled by me!
 
All the best and thanks a lot!

**Comment by laletuver1** [comment]
[EU Periodic Financial Report 2024](https://docs.google.com/document/d/1IVacqAPeb2-Rfkl57uEUyrrbubc1h5TZWeT7TcZz5jg/edit?usp=drive_link)
